name: Post welcome comment
on:
   pull_request:
     types: [opened]
jobs:
  build:
    name: Poste welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Hi this is a bot and I just wanted to remind you that you should be a CODEOWNER (see CODEOWNER.md), thanks for contributing to this awesome repository."
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
