  name: pull_request_comment
  on: 
    pull_request:
      types: [opened}
  jobs:
    build: 
      name: post_comments
      runs-on: ubuntu-latest
      steps:
        - run: gh pr comment $PR_URL --body "Hi, I am a bot and this is an automated message, I just wanted to remind you that you should be a CODEOWNER (see CODEOWNER.md) to contribute. Thank you for taking the time to contribute to this repository!"
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
            PR_URL: ${{ github.event.pull_request.html_url }}
